'use client'
// import React, { useState } from 'react';
// import { ChevronDown, Search, HelpCircle, Zap, Shield, Clock } from 'lucide-react';

// const faqs = [
//   {
//     category: "Getting Started",
//     icon: Zap,
//     questions: [
//       {
//         q: "What types of laptops does Raza Computers buy?",
//         a: "We buy various laptop brands, including Dell, Lenovo, HP, Samsung, Asus, LG, Sony, etc."
//       },
//       {
//         q: "Why should I choose Raza Computers to buy old laptops?",
//         a: "There are several reasons to choose us for buying old laptops: "
//       }
//     ]
//   },
//   {
//     category: "Warranty & Support",
//     icon: Shield,
//     questions: [
//       {
//         q: "What's included in your warranty?",
//         a: "All laptops come with a 6-month comprehensive warranty covering hardware failures, battery issues, and screen defects. Extended 1-year and 2-year warranty options available at checkout."
//       },
//       {
//         q: "Do you offer free repairs?",
//         a: "Yes. Within warranty period, all repairs are completely free including pickup and delivery. We also offer same-day repair diagnostics for urgent issues."
//       },
//       {
//         q: "Can I return my laptop if I'm not satisfied?",
//         a: "Absolutely. 30-day no-questions-asked return policy. If you're not happy, we'll refund 100% of your money. Just keep the original packaging."
//       }
//     ]
//   },
//   {
//     category: "Technical Specs",
//     icon: Clock,
//     questions: [
//       {
//         q: "How do I know the laptop specs are accurate?",
//         a: "We provide full system diagnostic reports generated by professional tools. You'll receive screenshots of CPU-Z, HWiNFO, and battery health reports before delivery."
//       },
//       {
//         q: "Are the laptops upgradeable?",
//         a: "Most models support RAM and SSD upgrades. We offer free consultation on upgrade compatibility and can perform upgrades at cost price."
//       }
//     ]
//   }
// ];

// export default function FAQComponent() {
//   const [openItems, setOpenItems] = useState({});
//   const [searchTerm, setSearchTerm] = useState("");
//   const [selectedCategory, setSelectedCategory] = useState("all");

//   const toggleItem = (category, index) => {
//     const key = `${category}-${index}`;
//     setOpenItems(prev => ({
//       ...prev,
//       [key]: !prev[key]
//     }));
//   };

//   const filteredFaqs = faqs.map(category => ({
//     ...category,
//     questions: category.questions.filter(item =>
//       (selectedCategory === "all" || category.category === selectedCategory) &&
//       (item.q.toLowerCase().includes(searchTerm.toLowerCase()) ||
//        item.a.toLowerCase().includes(searchTerm.toLowerCase()))
//     )
//   })).filter(category => category.questions.length > 0);

//   return (
//     <div className="min-h-screen w-full bg-gradient-to-br from-slate-50 via-blue-50 to-slate-100 py-12 px-4 sm:px-6 lg:px-8">
//       <div className="max-w-5xl mx-auto">
//         {/* Header */}
//         <div className="text-center mb-12">
//           <div className="inline-flex items-center justify-center w-16 h-16 bg-blue-600 rounded-2xl mb-4 shadow-lg">
//             <HelpCircle className="w-8 h-8 text-white" />
//           </div>
//           <h1 className="text-4xl sm:text-5xl font-bold text-gray-900 mb-3">
//             Frequently Asked Questions
//           </h1>
//           <p className="text-lg text-gray-600 max-w-2xl mx-auto">
//             Got questions? We've got answers. Can't find what you're looking for? Contact our support team.
//           </p>
//         </div>

//         {/* Search Bar */}
//         <div className="mb-8 relative">
//           <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
//           <input
//             type="text"
//             placeholder="Search your question..."
//             value={searchTerm}
//             onChange={(e) => setSearchTerm(e.target.value)}
//             className="w-full pl-12 pr-4 py-4 rounded-2xl border-2 border-gray-200 focus:border-blue-500 focus:outline-none shadow-sm text-gray-900 placeholder-gray-400 transition-all"
//           />
//         </div>

//         {/* Category Filter */}
//         <div className="flex flex-wrap gap-3 mb-10 justify-center">
//           <button
//             onClick={() => setSelectedCategory("all")}
//             className={`px-6 py-2.5 rounded-full font-medium transition-all ${
//               selectedCategory === "all"
//                 ? "bg-blue-600 text-white shadow-lg shadow-blue-200"
//                 : "bg-white text-gray-700 hover:bg-gray-50 border border-gray-200"
//             }`}
//           >
//             All Questions
//           </button>
//           {faqs.map((category) => (
//             <button
//               key={category.category}
//               onClick={() => setSelectedCategory(category.category)}
//               className={`px-6 py-2.5 rounded-full font-medium transition-all flex items-center gap-2 ${
//                 selectedCategory === category.category
//                   ? "bg-blue-600 text-white shadow-lg shadow-blue-200"
//                   : "bg-white text-gray-700 hover:bg-gray-50 border border-gray-200"
//               }`}
//             >
//               <category.icon className="w-4 h-4" />
//               {category.category}
//             </button>
//           ))}
//         </div>

//         {/* FAQ Items */}
//         <div className="space-y-8">
//           {filteredFaqs.map((category) => (
//             <div key={category.category} className="space-y-3">
//               <div className="flex items-center gap-3 mb-4">
//                 <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-blue-600 rounded-xl flex items-center justify-center shadow-md">
//                   <category.icon className="w-5 h-5 text-white" />
//                 </div>
//                 <h2 className="text-2xl font-bold text-gray-900">{category.category}</h2>
//               </div>

//               {category.questions.map((item, index) => {
//                 const key = `${category.category}-${index}`;
//                 const isOpen = openItems[key];

//                 return (
//                   <div
//                     key={index}
//                     className="bg-white rounded-2xl shadow-sm hover:shadow-md transition-all border border-gray-100 overflow-hidden"
//                   >
//                     <button
//                       onClick={() => toggleItem(category.category, index)}
//                       className="w-full px-6 py-5 flex items-start justify-between gap-4 text-left hover:bg-gray-50 transition-colors"
//                     >
//                       <span className="font-semibold text-gray-900 text-lg flex-1 leading-relaxed">
//                         {item.q}
//                       </span>
//                       <ChevronDown
//                         className={`w-6 h-6 text-blue-600 flex-shrink-0 transition-transform duration-300 ${
//                           isOpen ? "rotate-180" : ""
//                         }`}
//                       />
//                     </button>

//                     <div
//                       className={`overflow-hidden transition-all duration-300 ease-in-out ${
//                         isOpen ? "max-h-96" : "max-h-0"
//                       }`}
//                     >
//                       <div className="px-6 pb-5 pt-0">
//                         <div className="pl-4 border-l-4 border-blue-500">
//                           <p className="text-gray-700 leading-relaxed">{item.a}</p>
//                         </div>
//                       </div>
//                     </div>
//                   </div>
//                 );
//               })}
//             </div>
//           ))}

//           {filteredFaqs.length === 0 && (
//             <div className="text-center py-16">
//               <div className="w-20 h-20 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
//                 <Search className="w-10 h-10 text-gray-400" />
//               </div>
//               <p className="text-xl text-gray-600">No results found for "{searchTerm}"</p>
//               <p className="text-gray-500 mt-2">Try a different search term or browse all categories</p>
//             </div>
//           )}
//         </div>

//         {/* Contact CTA */}
//         <div className="mt-16 bg-gradient-to-r from-blue-600 to-blue-700 rounded-3xl p-8 sm:p-10 text-center shadow-xl">
//           <h3 className="text-2xl sm:text-3xl font-bold text-white mb-3">
//             Still have questions?
//           </h3>
//           <p className="text-blue-100 mb-6 text-lg">
//             Our support team is ready to help you 24/7
//           </p>
//           <div className="flex flex-col sm:flex-row gap-4 justify-center">
//             <button className="px-8 py-3.5 bg-white text-blue-600 font-semibold rounded-xl hover:bg-gray-50 transition-colors shadow-lg">
//               Contact Support
//             </button>
//             <button className="px-8 py-3.5 bg-blue-800 text-white font-semibold rounded-xl hover:bg-blue-900 transition-colors">
//               WhatsApp Us
//             </button>
//           </div>
//         </div>
//       </div>
//     </div>
//   );
// }


import React, { useState } from 'react';
import { ChevronDown, Search, HelpCircle, Zap, Shield, Clock, CheckCircle } from 'lucide-react';

const faqs = [
  {
    category: "Getting Started",
    icon: Zap,
    questions: [
      {
        q: "How quickly can I get my laptop delivered?",
        a: "We offer same-day delivery within city limits for orders placed before 2 PM. Outside city limits, expect delivery within 24-48 hours. All laptops come with real-time tracking.",
        subPoints: [
          {
            title: "Same-Day Delivery",
            description: "Available for orders within 50km radius placed before 2 PM"
          },
          {
            title: "Express Delivery",
            description: "24-hour guaranteed delivery for metro cities"
          },
          {
            title: "Standard Delivery",
            description: "48-hour delivery for all other locations across India"
          }
        ]
      },
      {
        q: "What makes your refurbished laptops different?",
        a: "Every laptop undergoes a 50-point quality check, complete hardware diagnostics, and professional cleaning. We replace batteries below 80% health and provide a detailed condition report with every purchase.",
        subPoints: [
          {
            title: "Hardware Inspection",
            description: "CPU, RAM, motherboard tested under stress conditions"
          },
          {
            title: "Display Testing",
            description: "Dead pixel check, backlight bleeding, color calibration"
          },
          {
            title: "Battery Certification",
            description: "Minimum 80% health or free replacement included"
          },
          {
            title: "Deep Cleaning",
            description: "Keyboard, vents, screen professionally sanitized"
          }
        ]
      }
    ]
  },
  {
    category: "Warranty & Support",
    icon: Shield,
    questions: [
      {
        q: "What's included in your warranty?",
        a: "All laptops come with a 6-month comprehensive warranty covering hardware failures, battery issues, and screen defects. Extended 1-year and 2-year warranty options available at checkout.",
        subPoints: [
          {
            title: "Hardware Coverage",
            description: "Motherboard, processor, RAM, hard drive failures"
          },
          {
            title: "Display Protection",
            description: "Dead pixels, backlight issues, screen flickering"
          },
          {
            title: "Battery Guarantee",
            description: "Drops below 70% health within warranty period"
          },
          {
            title: "What's NOT Covered",
            description: "Physical damage, liquid spills, software issues, accidental drops"
          }
        ]
      },
      {
        q: "Do you offer free repairs?",
        a: "Yes. Within warranty period, all repairs are completely free including pickup and delivery. We also offer same-day repair diagnostics for urgent issues."
      },
      {
        q: "Can I return my laptop if I'm not satisfied?",
        a: "Absolutely. 30-day no-questions-asked return policy. If you're not happy, we'll refund 100% of your money. Just keep the original packaging.",
        subPoints: [
          {
            title: "30-Day Window",
            description: "Full refund if returned within 30 days of delivery"
          },
          {
            title: "Original Packaging Required",
            description: "Keep the box and accessories for hassle-free returns"
          },
          {
            title: "Instant Refund",
            description: "Money back within 3-5 business days after inspection"
          }
        ]
      }
    ]
  },
  {
    category: "Technical Specs",
    icon: Clock,
    questions: [
      {
        q: "How do I know the laptop specs are accurate?",
        a: "We provide full system diagnostic reports generated by professional tools. You'll receive screenshots of CPU-Z, HWiNFO, and battery health reports before delivery.",
        subPoints: [
          {
            title: "CPU-Z Report",
            description: "Processor model, cores, clock speeds verified"
          },
          {
            title: "HWiNFO Analysis",
            description: "Complete hardware inventory and health status"
          },
          {
            title: "Battery Report",
            description: "Cycle count, design capacity vs current capacity"
          },
          {
            title: "Video Proof",
            description: "Optional live video inspection before shipping"
          }
        ]
      },
      {
        q: "Are the laptops upgradeable?",
        a: "Most models support RAM and SSD upgrades. We offer free consultation on upgrade compatibility and can perform upgrades at cost price.",
        subPoints: [
          {
            title: "RAM Upgrades",
            description: "Check if your model has available slots"
          },
          {
            title: "SSD Installation",
            description: "Upgrade from HDD to SSD for 3x faster performance"
          },
          {
            title: "Professional Installation",
            description: "We install upgrades at cost with no service charges"
          }
        ]
      }
    ]
  }
];

export default function FAQComponent() {
  const [openItems, setOpenItems] = useState<Record<string, boolean>>({});
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedCategory, setSelectedCategory] = useState("all");

  const toggleItem = (category: string, index: number) => {
    const key = `${category}-${index}`;
    setOpenItems(prev => ({
      ...prev,
      [key]: !prev[key]
    }));
  };

  const filteredFaqs = faqs.map(category => ({
    ...category,
    questions: category.questions.filter(item =>
      (selectedCategory === "all" || category.category === selectedCategory) &&
      (item.q.toLowerCase().includes(searchTerm.toLowerCase()) ||
       item.a.toLowerCase().includes(searchTerm.toLowerCase()))
    )
  })).filter(category => category.questions.length > 0);

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-slate-100 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-5xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-blue-600 rounded-2xl mb-4 shadow-lg">
            <HelpCircle className="w-8 h-8 text-white" />
          </div>
          <h1 className="text-4xl sm:text-5xl font-bold text-gray-900 mb-3">
            Frequently Asked Questions
          </h1>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Got questions? We&apos;ve got answers. Can&apos;t find what you&apos;re looking for? Contact our support team.
          </p>
        </div>

        {/* Search Bar */}
        <div className="mb-8 relative">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
          <input
            type="text"
            placeholder="Search your question..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-12 pr-4 py-4 rounded-2xl border-2 border-gray-200 focus:border-blue-500 focus:outline-none shadow-sm text-gray-900 placeholder-gray-400 transition-all"
          />
        </div>

        {/* Category Filter */}
        <div className="flex flex-wrap gap-3 mb-10 justify-center">
          <button
            onClick={() => setSelectedCategory("all")}
            className={`px-6 py-2.5 rounded-full font-medium transition-all ${
              selectedCategory === "all"
                ? "bg-blue-600 text-white shadow-lg shadow-blue-200"
                : "bg-white text-gray-700 hover:bg-gray-50 border border-gray-200"
            }`}
          >
            All Questions
          </button>
          {faqs.map((category) => (
            <button
              key={category.category}
              onClick={() => setSelectedCategory(category.category)}
              className={`px-6 py-2.5 rounded-full font-medium transition-all flex items-center gap-2 ${
                selectedCategory === category.category
                  ? "bg-blue-600 text-white shadow-lg shadow-blue-200"
                  : "bg-white text-gray-700 hover:bg-gray-50 border border-gray-200"
              }`}
            >
              <category.icon className="w-4 h-4" />
              {category.category}
            </button>
          ))}
        </div>

        {/* FAQ Items */}
        <div className="space-y-8">
          {filteredFaqs.map((category) => (
            <div key={category.category} className="space-y-3">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-blue-600 rounded-xl flex items-center justify-center shadow-md">
                  <category.icon className="w-5 h-5 text-white" />
                </div>
                <h2 className="text-2xl font-bold text-gray-900">{category.category}</h2>
              </div>

              {category.questions.map((item, index) => {
                const key = `${category.category}-${index}`;
                const isOpen = openItems[key];

                return (
                  <div
                    key={index}
                    className="bg-white rounded-2xl shadow-sm hover:shadow-md transition-all border border-gray-100 overflow-hidden"
                  >
                    <button
                      onClick={() => toggleItem(category.category, index)}
                      className="w-full px-6 py-5 flex items-start justify-between gap-4 text-left hover:bg-gray-50 transition-colors"
                    >
                      <span className="font-semibold text-gray-900 text-lg flex-1 leading-relaxed">
                        {item.q}
                      </span>
                      <ChevronDown
                        className={`w-6 h-6 text-blue-600 flex-shrink-0 transition-transform duration-300 ${
                          isOpen ? "rotate-180" : ""
                        }`}
                      />
                    </button>

                    <div
                      className={`overflow-hidden transition-all duration-300 ease-in-out ${
                        isOpen ? "max-h-[1000px]" : "max-h-0"
                      }`}
                    >
                      <div className="px-6 pb-5 pt-0">
                        <div className="pl-4 border-l-4 border-blue-500">
                          <p className="text-gray-700 leading-relaxed mb-4">{item.a}</p>
                          
                          {item.subPoints && item.subPoints.length > 0 && (
                            <div className="space-y-3 mt-4">
                              {item.subPoints.map((point, idx) => (
                                <div key={idx} className="flex gap-3 bg-gradient-to-r from-blue-50 to-transparent p-3 rounded-lg border-l-2 border-blue-400">
                                  <CheckCircle className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" />
                                  <div className="flex-1">
                                    <h4 className="font-semibold text-gray-900 mb-1">
                                      {point.title}
                                    </h4>
                                    <p className="text-sm text-gray-600 leading-relaxed">
                                      {point.description}
                                    </p>
                                  </div>
                                </div>
                              ))}
                            </div>
                          )}
                        </div>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          ))}

          {filteredFaqs.length === 0 && (
            <div className="text-center py-16">
              <div className="w-20 h-20 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <Search className="w-10 h-10 text-gray-400" />
              </div>
              <p className="text-xl text-gray-600">No results found for &quot;{searchTerm}&quot;</p>
              <p className="text-gray-500 mt-2">Try a different search term or browse all categories</p>
            </div>
          )}
        </div>

        {/* Contact CTA */}
        <div className="mt-16 bg-gradient-to-r from-blue-600 to-blue-700 rounded-3xl p-8 sm:p-10 text-center shadow-xl">
          <h3 className="text-2xl sm:text-3xl font-bold text-white mb-3">
            Still have questions?
          </h3>
          <p className="text-blue-100 mb-6 text-lg">
            Our support team is ready to help you 24/7
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <button className="px-8 py-3.5 bg-white text-blue-600 font-semibold rounded-xl hover:bg-gray-50 transition-colors shadow-lg">
              Contact Support
            </button>
            <button className="px-8 py-3.5 bg-blue-800 text-white font-semibold rounded-xl hover:bg-blue-900 transition-colors">
              WhatsApp Us
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}